In [1]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
from math import ceil
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.utils import shuffle
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from numpy import load

In [2]:
# load dict of arrays
dict_data = load('data.npz')
# extract the first array
X = dict_data['arr_0']

# load dict of arrays
dict_data = load('ytrain_label.npz')
# extract the first array
y = dict_data['arr_0']

In [3]:
splitter = StratifiedShuffleSplit(n_splits=1, test_size=0.4, random_state=0)

for train_idx, test_idx in splitter.split(X, y):
    xtrain = [X[i] for i in train_idx]
    ytrain = [y[i] for i in train_idx]
    xtest = [X[i] for i in test_idx]
    ytest = [y[i] for i in test_idx]

xtrain = np.array(xtrain)
ytrain = np.array(ytrain)
xtest = np.array(xtest)
ytest = np.array(ytest)

In [ ]:
# Train in batch:
logmod = SGDClassifier(loss="log_loss", n_jobs=-1, max_iter=1000)
batch_size = 100000
max_len = len(xtrain)
num_batch = ceil(max_len / batch_size)
for epoch in range(10):
    X, y = shuffle(xtrain, ytrain)
    for i in range(num_batch):
        if i == num_batch - 1:
            logmod.partial_fit(xtrain[i * batch_size : max_len], ytrain[i * batch_size : max_len], classes=[0, 1, 2])
        else:
            logmod.partial_fit(xtrain[i * batch_size : (i + 1) * batch_size], ytrain[i * batch_size : (i + 1) * batch_size], classes=[0, 1, 2])

In [12]:
# logmod = LogisticRegression(solver="lbfgs", max_iter=500).fit(xtrain, ytrain)

In [5]:
ypred = logmod.predict(xtrain)

print(accuracy_score(ytrain, ypred))
print(confusion_matrix(ytrain, ypred))

0.3332976637417602
[[      3       0  999943]
 [      0       0 1000000]
 [      0       0  999808]]
